--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 8.0.864
--   Created On : 星期一, 28 十一月, 2016 
--   DBMS       : MySql 
--   -------------------------------------------------- 

USE saleshare;

SET FOREIGN_KEY_CHECKS=0;


--  Drop Tables, Stored Procedures and Views 

DROP TABLE IF EXISTS demo;
DROP TABLE IF EXISTS sys_menu_fun;
DROP TABLE IF EXISTS sys_org;
DROP TABLE IF EXISTS sys_role;
DROP TABLE IF EXISTS sys_role_fun;
DROP TABLE IF EXISTS sys_user;
DROP TABLE IF EXISTS sys_user_org;
DROP TABLE IF EXISTS sys_user_role;

--  Create Tables 
CREATE TABLE demo
(
	id INTEGER NOT NULL AUTO_INCREMENT,
	descs VARCHAR(255),
	code INTEGER,
	PRIMARY KEY (id),
	UNIQUE UQ_demo_id(id)
) ;


CREATE TABLE sys_menu_fun
(
	id INTEGER NOT NULL AUTO_INCREMENT,
	name VARCHAR(250) COMMENT '功能名称',
	fun_code VARCHAR(100) COMMENT '功能编码',
	fun_type INTEGER DEFAULT 0 COMMENT '功能类型,0:功能点 1:菜单',
	parent_menu INTEGER COMMENT '父菜单',
	fun_url VARCHAR(255) COMMENT '功能访问地址',
	create_time TIMESTAMP,
	create_user INTEGER COMMENT '生成此功能用户',
	last_modify_time TIMESTAMP COMMENT '上次修改时间',
	last_modify_user INTEGER COMMENT '上次修改用户',
	PRIMARY KEY (id),
	UNIQUE UQ_sys_menu_fun_id(id)
)  COMMENT='菜单功能';


CREATE TABLE sys_org
(
	id INTEGER NOT NULL AUTO_INCREMENT,
	is_valid INTEGER DEFAULT 1 COMMENT '是否有效, 1:有效 0:无效',
	org_code VARCHAR(100) COMMENT '机构编码',
	org_name VARCHAR(250) COMMENT '机构名称',
	parent_org INTEGER COMMENT '上级机构ID',
	org_desc TEXT COMMENT '机构描述',
	create_time TIMESTAMP COMMENT '创建时间',
	create_user INTEGER COMMENT '创建用户ID',
	last_modify_time TIMESTAMP COMMENT '上次修改时间',
	last_modify_user INTEGER COMMENT '上次修改用户',
	PRIMARY KEY (id),
	UNIQUE UQ_sys_org_id(id)
)  COMMENT='机构信息';


CREATE TABLE sys_role
(
	id INTEGER NOT NULL,
	role_name VARCHAR(150) COMMENT '角色名称',
	role_code VARCHAR(100) COMMENT '角色编码',
	is_delete INTEGER COMMENT '是否删除,0:否 1:是',
	create_time TIMESTAMP COMMENT '新增时间',
	create_user INTEGER COMMENT '新增此角色用户Id',
	last_modify_time TIMESTAMP COMMENT '修改时间',
	last_modify_user INTEGER COMMENT '修改此角色用户ID',
	PRIMARY KEY (id),
	UNIQUE UQ_sys_role_id(id)
)  COMMENT='角色表';


CREATE TABLE sys_role_fun
(
	id INTEGER NOT NULL AUTO_INCREMENT,
	role_id INTEGER COMMENT '角色ID',
	fun_id INTEGER COMMENT '功能ID',
	create_time TIMESTAMP COMMENT '创建时间',
	create_user INTEGER COMMENT '创建用户ID',
	last_modify_time TIMESTAMP COMMENT '最后修改时间',
	last_modify_user INTEGER COMMENT '最后修改用户ID',
	PRIMARY KEY (id),
	UNIQUE UQ_sys_role_fun_id(id)
)  COMMENT='角色功能关系表';


CREATE TABLE sys_user
(
	id INTEGER NOT NULL AUTO_INCREMENT,
	user_name VARCHAR(100),
	password VARCHAR(250),
	user_status INTEGER DEFAULT 1 COMMENT '用户状态,1:正常 2:删除',
	create_time TIMESTAMP COMMENT '生成时间',
	create_user INTEGER COMMENT '生成用户',
	last_modify_time TIMESTAMP COMMENT '最后修改时间 ',
	last_modify_user INTEGER COMMENT '最后修改用户',
	PRIMARY KEY (id),
	UNIQUE UQ_user_id(id)
) ;


CREATE TABLE sys_user_org
(
	id INTEGER NOT NULL AUTO_INCREMENT,
	user_id INTEGER COMMENT '用户ID',
	org_id INTEGER COMMENT '机构ID',
	create_time TIMESTAMP COMMENT '生成时间',
	create_user INTEGER COMMENT '生成用户',
	last_modify_time TIMESTAMP COMMENT '上次修改时间',
	last_modify_user INTEGER COMMENT '上次修改用户',
	PRIMARY KEY (id),
	UNIQUE UQ_sys_user_org_id(id)
)  COMMENT='用户机构关系表';


CREATE TABLE sys_user_role
(
	id INTEGER NOT NULL AUTO_INCREMENT,
	user_id INTEGER COMMENT '用户ID',
	role_id INTEGER COMMENT '角色ID',
	create_time TIMESTAMP COMMENT '生成时间',
	create_user INTEGER COMMENT '生成用户ID',
	last_modify_time TIMESTAMP COMMENT '最后修改时间',
	last_modify_user INTEGER COMMENT '最后修改用户ID',
	PRIMARY KEY (id),
	UNIQUE UQ_sys_user_role_id(id)
)  COMMENT='用户角色关系表';



SET FOREIGN_KEY_CHECKS=1;
